### ISSUE TITLE
🐛 [Bug]

### ISSUE THREAD

**Issue by Yuhenan** [bing2008/VMangos-eluna#1]
Hello, this PLAYER_EVENT_ON_LEVEL_CHANGE doesn't work   --vanilla bropack v20

**Comment by Yuhenan** [comment]
> Hello, this PLAYER_EVENT_ON_LEVEL_CHANGE doesn't work
vanilla bropack v20

**Comment by bing2008** [comment]
https://github.com/bing2008/VMangos-eluna/commit/4845e456c24f59d643d83be9e77e0f215dcb2937
