### ISSUE TITLE
🐛 [Bug]RegisterInstanceEvent无法生效

### ISSUE THREAD

**Issue by zbhcn** [bing2008/VMangos-eluna#10]
没有传递创建副本和玩家进入副本的钩子。
同时RegisterMapEvent好像也无法生效。

**Comment by bing2008** [comment]
RegisterMapEvent 应该是没有被使用，可以用 RegisterServerEvent 代替。

see：https://github.com/bing2008/eluna_script/commit/aa3687071fc61425a5ece328f76bcd06eedc65cc
