### ISSUE TITLE
🐛 [Bug]About compile 

### ISSUE THREAD

**Issue by Soulyes** [bing2008/VMangos-eluna#15]
1. compile release “not include revision.h”
2. cmake not any error
3. Download "https://github.com/ElunaLuaEngine/Eluna" put in "modules\Eluna"

**Comment by Soulyes** [comment]
i copy old ver revision.h
but the Eluna more error
![image](https://github.com/bing2008/VMangos-eluna/assets/147594856/838e4d4a-2919-4804-8897-fc4b8d3082a1)

**Comment by Niam5** [comment]
When you clone the repository now you need to use "git clone --recursive https://github.com/bing2008/VMangos-eluna.git" as Eluna is now submoduled. Using that command will get the correct Eluna version and place it where it needs to be. Grabbing the files from the Eluna repository and placing them manually may have unintended consequences as it may be further ahead then this projects current requirements. Please try the above clone command and attempt a rebuild afterwards.

**Comment by Soulyes** [comment]
thanks，Compilation successful.
