### ISSUE TITLE
🐛 [Bug] PLAYER_EVENT_ON_COMMAND  looks doesn't work anymore

### ISSUE THREAD

**Issue by oowow-core** [bing2008/VMangos-eluna#20]
## 🐛 Bug report

--PLAYER_EVENT_ON_COMMAND =     42       -- (event, player, command) - Can return false
RegisterPlayerEvent(42, CMD.Input)

all command doesn't work now

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by bing2008** [comment]
Fix the issue: https://github.com/bing2008/VMangos-eluna/commit/dcf59b62670b1e1d892fc2ceefa85b05a69a099f

Use this code to test it.

```local PLAYER_EVENT_ON_COMMAND = 42 -- (event, player, command) - player is nil if command used from console. Can return false
local function Player_Command(event,player,command)
	player:SendBroadcastMessage("Player_Command:player:"..player:GetName().." input: "..command)
end
local isCancel = RegisterPlayerEvent( PLAYER_EVENT_ON_COMMAND, Player_Command )
```

**Comment by oowow-core** [comment]
works, thanks!
