### ISSUE TITLE
🐛 [Bug]The quest to open the upper level of Blackrock Tower and Urok cannot be completed.

### ISSUE THREAD

**Issue by yybss** [bing2008/VMangos-eluna#24]
1.The Emberstrife mission cannot be completed during the dragon control phase, prompting an invalid target
2.Using Ormoc's head in the Urok tribute pile prompts an invalid target

The client version is 1.12.1

**Comment by bing2008** [comment]
If there issues about VMangos, please report it in original version: https://github.com/vmangos/core/issues
