### ISSUE TITLE
H，in code TODO: 0 is magic number for "addAuraFlags"

### ISSUE THREAD

**Issue by Yuhenan** [bing2008/VMangos-eluna#5]
H, in code

#elif defined VMANGOS

Eluna::Push(L, unit->AddAura(spell, 0, target)); // TODO: 0 is magic number for "addAuraFlags"

I don't understand！···

I made mistakes like this  "player:AddAura(35001, 0, player)" 

Console display  ERROR: lua_scripts/npc_TF.lua:182: bad argument #2 to 'AddAura' (bad argument : Unit expected, got number)

thank you！···

**Comment by bing2008** [comment]
You don't need to add the secend argument when using lua API, just "player:AddAura(35001, player)". see: http://elunaluaengine.github.io/Unit/AddAura.html

**Comment by Yuhenan** [comment]
> 使用 lua API 时不需要添加 secend 参数，只需添加 “player：AddAura（35001， player）”。参见：http://elunaluaengine.github.io/Unit/AddAura.html


thank you, if  "player:AddAura(35001, player)"   core report errors "ERROR: (null) missing metatable"  。。。I cancel。QQQ

**Comment by bing2008** [comment]
Oh, yes you rae right! I am sorry i don't notice the error on console.

I am going to find out why...

**Comment by bing2008** [comment]
Fixed. see: https://github.com/bing2008/VMangos-eluna/commit/1a4fb136582482033150fba211b5718b857312fb

**Comment by Yuhenan** [comment]
> 固定。请参阅： [1A4FB13](https://github.com/bing2008/VMangos-eluna/commit/1a4fb136582482033150fba211b5718b857312fb)
Thank you very much！~
